version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 3
    schedule:
      interval: "weekly"
    groups:
      rslib:
        patterns:
          - "@rslib/*"
          - "rsbuild-plugin-dts"
